server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev
    # active: dev
  data:
    redis:
      host: 47.115.205.198
      port: 5432
      password: wLz80kDjq0OuplDHP
      database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.42.65:8848
