server:
  port: 8002

dubbo:
  application:
    name: short-link-web
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${link.nacos.ip}:${link.nacos.port}?username=${link.nacos.username}&password=${link.nacos.password}
  consumer:
    check: false
    timeout: 5000
    filter: tracing

spring:
  application:
    name: short-link-web
  redis:
    host: ${link.redis.ip}
    port: ${link.redis.port}
    database: ${link.redis.database}
    password: ${link.redis.password}
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  profiles:
    active: prod
logging:
  config: classpath:log4j2-spring.xml


zipkin:
  base:
    url: http://127.0.0.1:9411/api/v2/spans
  enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}