server:
  port: 8002

dubbo:
  application:
    name: shortlink-web
  protocol:
    name: dubbo
  registry:
    address: nacos://8.130.42.65:8848?username=nacos&password=nacos
  consumer:
    check: false
    timeout: 5000

knife4j:
  # 开启增强配置
  enable: true
  setting:
    # 是否启用Host
    enable-host: false
    enable-host-text: www
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 豫ICP备2024074573号
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md
    enable-search: false
spring:
  application:
    name: short-link-web
  data:
    ##############redis#################
    redis:
      host: 124.220.44.196
      port: 9991
      password: iFRQYImbNzwT6Q5P8Uoy
      database: 2
  mvc:
    view:
      prefix: /templates/
      suffix: .html
logging:
  config: classpath:log4j2-spring.xml