server:
  port: 8002

dubbo:
  application:
    name: short-link-web
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${link.nacos.ip}:${link.nacos.port}?username=${link.nacos.username}&password=${link.nacos.password}
  consumer:
    check: false
    timeout: 5000

spring:
  application:
    name: short-link-web
  data:
    ##############redis#################
    redis:
      host: ${link.redis.ip}
      port: ${link.redis.port}
      password: ${link.redis.password}
      database: ${link.redis.database}
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  profiles:
    active: prod
logging:
  config: classpath:log4j2-spring.xml