server:
  port: 8002

dubbo:
  application:
    name: shortlink-web
  protocol:
    name: dubbo
  registry:
    address: nacos://8.130.42.65:8848?username=nacos&password=nacos
  consumer:
    check: false

spring:
  #############数据源#############
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml

  data:
    ##############redis#################
    redis:
      host: 124.220.44.196
      port: 9991
      password: iFRQYImbNzwT6Q5P8Uoy
      database: 2


logging:
  config: classpath:log4j2-spring.xml