server:
  port: 8002

dubbo:
  application:
    name: shortlink-web
  protocol:
    name: dubbo
  registry:
    address: nacos://8.130.42.65:8848?username=nacos&password=nacos
  consumer:
    check: false


logging:
  config: classpath:log4j2-spring.xml