server:
  port: 8002

dubbo:
  application:
    name: short-link-web
  protocol:
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
  consumer:
    check: false
    timeout: 5000

spring:
  application:
    name: short-link-web
  data:
    ##############redis#################
    redis:
      host: 116.198.205.100
      port: 9991
      password: iFRQYImbNzwT6Q5P8Uoy
      database: 2
  mvc:
    view:
      prefix: /templates/
      suffix: .html
logging:
  config: classpath:log4j2-spring.xml