server:
  port: 8002

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:13306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 8.130.99.203
      port: 6336
      password: 123456
      database: 2