server:
  port: 8002

spring:
  #############数据源#############
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml

  data:
    ##############redis#################
    redis:
      host: 47.115.205.198
      port: 5432
      password: wLz80kDjq0OuplDHP
      database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.42.65:8848