dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://124.220.44.196:9992/link_core_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WEbXHFtmQ6votVGeIFHK
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://124.220.44.196:9992/link_core_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WEbXHFtmQ6votVGeIFHK
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://124.220.44.196:9992/link_user_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WEbXHFtmQ6votVGeIFHK
  ds_3:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://124.220.44.196:9992/link_user_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WEbXHFtmQ6votVGeIFHK

rules:
  - !SHARDING
    tables:
      #################################project-rules##############################################
      t_link:
        actualDataNodes: ds_0.t_link_${0..2}
        #分库策略
        databaseStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: link_database_complex_mod
        tableStrategy:
          complex:
            shardingColumns: gid,username
            shardingAlgorithmName: link_table_complex_mod
      t_link_goto:
        actualDataNodes: ds_0.t_link_goto_${0..2}
        #分库策略
        databaseStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: link_goto_database_complex_mod
        tableStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: link_goto_table_hash_mod
      t_link_access_logs:
        actualDataNodes: ds_0.t_link_access_logs
      t_link_access_stats:
        actualDataNodes: ds_0.t_link_access_stats
      t_link_browser_stats:
        actualDataNodes: ds_0.t_link_browser_stats
      t_link_device_stats:
        actualDataNodes: ds_0.t_link_device_stats
      t_link_locale_stats:
        actualDataNodes: ds_0.t_link_locale_stats
      t_link_network_stats:
        actualDataNodes: ds_0.t_link_network_stats
      t_link_os_stats:
        actualDataNodes: ds_0.t_link_os_stats
      t_link_stats_today:
        actualDataNodes: ds_0.t_link_stats_today
      #################################admin-rules##############################################
      t_user:
        # 真实数据节点，比如数据库源以及数据库在数据库中真实存在的
        actualDataNodes: ds_${2..3}.t_user_${0..5}
        #分库策略
        databaseStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_database_hash_mod
        # 分表策略
        tableStrategy:
          # 用于单分片键的标准分片场景
          standard:
            # 分片键
            shardingColumn: username
            # 分片算法，对应 rules[0].shardingAlgorithms
            shardingAlgorithmName: user_table_hash_mod
      t_group:
        actualDataNodes: ds_${2..3}.t_group_${0..5}
        #分库策略
        databaseStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: group_database_hash_mod
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: group_table_hash_mod
      #################################data-ext-rules不进行分库分表##############################################
#      t_link_access_logs:
#        actualDataNodes: ds_4.t_link_access_logs
#      t_link_access_stats:
#        actualDataNodes: ds_4.t_link_access_stats
#      t_link_browser_stats:
#        actualDataNodes: ds_4.t_link_browser_stats
#      t_link_device_stats:
#        actualDataNodes: ds_4.t_link_device_stats
#      t_link_locale_stats:
#        actualDataNodes: ds_4.t_link_locale_stats
#      t_link_network_stats:
#        actualDataNodes: ds_4.t_link_network_stats
#      t_link_os_stats:
#        actualDataNodes: ds_4.t_link_os_stats
#      t_link_stats_today:
#        actualDataNodes: ds_4.t_link_stats_today
    shardingAlgorithms:
#################################project-shardingAlgorithms##############################################
      link_database_complex_mod:
        type: CLASS_BASED
        props:
          sharding-count: 6
          table-sharding-count: 3
          strategy: standard
          algorithmClassName: com.ispengya.shortlink.common.sharding.CustomProjectDbHashModShardingAlgorithm
      link_goto_database_complex_mod:
        type: CLASS_BASED
        props:
          sharding-count: 6
          table-sharding-count: 3
          strategy: standard
          algorithmClassName: com.ispengya.shortlink.common.sharding.CustomProjectDbHashModShardingAlgorithm
      link_table_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: com.ispengya.shortlink.common.sharding.LinkCommonTableComplexAlgorithm
          #临时更换3
          sharding-count: 3
          #临时更换1
          table-sharding-count: 1
          database-count: 2
          strategy: complex
      link_goto_table_hash_mod:
        type: HASH_MOD
        props:
          #临时更换3
          sharding-count: 3
      #################################admin-shardingAlgorithms##############################################
      user_database_hash_mod:
        type: CLASS_BASED
        props:
          sharding-count: 6
          table-sharding-count: 3
          strategy: standard
          algorithmClassName: com.ispengya.shortlink.common.sharding.CustomAdminDbHashModShardingAlgorithm
      group_database_hash_mod:
        type: CLASS_BASED
        props:
          sharding-count: 6
          table-sharding-count: 3
          strategy: standard
          algorithmClassName: com.ispengya.shortlink.common.sharding.CustomAdminDbHashModShardingAlgorithm
      # 数据表分片算法
      user_table_hash_mod:
        # 根据分片键 Hash 分片
        type: HASH_MOD
        # 分片数量
        props:
          sharding-count: 6
      group_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 6
  # 数据加密存储规则
  - !ENCRYPT
    # 需要加密的表集合
    tables:
      # 用户表
      t_user:
        # 用户表中哪些字段需要进行加密
        columns:
          # 手机号字段，逻辑字段，不一定是在数据库中真实存在
          phone:
            # 手机号字段存储的密文字段，这个是数据库中真实存在的字段
            cipherColumn: phone
            # 身份证字段加密算法
            encryptorName: common_encryptor
          mail:
            cipherColumn: mail
            encryptorName: common_encryptor
        # 是否按照密文字段查询
        queryWithCipherColumn: true
    # 加密算法
    encryptors:
      # 自定义加密算法名称
      common_encryptor:
        # 加密算法类型
        type: AES
        props:
          # AES 加密密钥
          aes-key-value: d6oadClrrbssaa9A3GWo
props:
  sql-show: true
